// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpRT8gdlgDNUiivIsGLcq2nm166ClD1nE',
    appId: '1:261565397483:web:104d978fc9c49ee136c1ae',
    messagingSenderId: '261565397483',
    projectId: 'news-c84d0',
    authDomain: 'news-c84d0.firebaseapp.com',
    storageBucket: 'news-c84d0.appspot.com',
    measurementId: 'G-R71W67BXLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwdmrwNl5Rmj3UTNApkA_UhAoLWNThI5U',
    appId: '1:261565397483:android:b19f918f3cc46aa036c1ae',
    messagingSenderId: '261565397483',
    projectId: 'news-c84d0',
    storageBucket: 'news-c84d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDECu9BVBzE7g9OJeVUg1HZVAoPj_gWloI',
    appId: '1:261565397483:ios:430ab9146de937aa36c1ae',
    messagingSenderId: '261565397483',
    projectId: 'news-c84d0',
    storageBucket: 'news-c84d0.appspot.com',
    androidClientId: '261565397483-ohh1e8rmlons95dodjdkmd3cprj04vlj.apps.googleusercontent.com',
    iosClientId: '261565397483-cidkp2l3sg19jel1cogtnrirs9m8skm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.news',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDECu9BVBzE7g9OJeVUg1HZVAoPj_gWloI',
    appId: '1:261565397483:ios:fb4bc62e634f662b36c1ae',
    messagingSenderId: '261565397483',
    projectId: 'news-c84d0',
    storageBucket: 'news-c84d0.appspot.com',
    androidClientId: '261565397483-ohh1e8rmlons95dodjdkmd3cprj04vlj.apps.googleusercontent.com',
    iosClientId: '261565397483-t3e0hk9h3utrb9uffblcr8ugmb4aksom.apps.googleusercontent.com',
    iosBundleId: 'com.example.news.RunnerTests',
  );
}
